# sample example of a Pod which consists of a container running the image nginx:1.14.2.


apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80


To create the Pod
kubectl apply -f https://k8s.io/examples/pods/simple-pod.yaml
